#This workflow creates a file with the merges for the current branch

name: Commits_on_tag_two

on:
#Enable to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - '*'


jobs:
  call-workflow-in-another-repo:
    uses: Zivra/github-automation/.github/workflows/simple_test.yml@main
    
