# This workflow creates a file with the commits of the repositories belonging to a team

name: Consolidate_teams_repos

on:
# Enable to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:

jobs:
  build_repo_list:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Repos and store in file
      run: |
        curl -i -H "Authorization: token ${{ secrets.API_TOKEN }}" https://api.github.com/teams/6746665/repos | grep "full_name" > repo_list.txt
        sed -e s/[full_name,\",:,\,]//g -i repo_list.txt
        echo repo_list.txt

#repo1_commit:
#    runs-on: ubuntu-latest

#    steps:
#    - uses: actions/checkout@v3
#      with:
#        repository: Zivra/check_secrets
#        token: ${{ secrets.API_TOKEN }}
#        fetch-depth: 0
#    - name: Insert Repo Name
#      run: echo "Repo:Check Secrets" > commits1.csv
#    - name: Insert Headers
#      run: echo "Repo,Name, Commit Date, Commit Msg" >> commits1.csv
#    - name: Get Commits List
#      run: git log --pretty=format:"%aN, %ad, %s" --no-merges >> commits1.csv
#    - name: Add Repo Name column
#      run: sed -i '3,$ s/^/Check_Secrets,/' commits1.csv
#    - name: Add empty line  
#      run: echo -e "\n" >> commits1.csv
#    - name: Get File as Artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: commit_report_1
#        path: ./commits1.csv
        
        
#  sumarize_commit:
#    runs-on: ubuntu-latest
#    needs: [ repo1_commit,repo2_commit ]
#    steps:
#    - name: Get Artifacts
#      # using download-artifact without specifying a name will download all the available artifacts
#      uses: actions/download-artifact@v3
#    - name: check files
#      run: ls -R
#    - name: get_commit_1
#      run: cp ./commit_report_1/commits1.csv .     
#    - name: get_commit_2
#      run: cp ./commit_report_2/commits2.csv .
#    - name: Consolidate Report
#      run: cat ./commits*.csv >> ./summarized.csv       
#    - name: Get File as Artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: Commit Report
#        path: ./summarized.csv
#    - name: Send mail
#      uses: dawidd6/action-send-mail@v3
#      with:
#        server_address: email-smtp.us-west-2.amazonaws.com
#        server_port: 465
#        secure: true
#        username: ${{secrets.MAIL_USERNAME}}
#        password: ${{secrets.MAIL_PASSWORD}}
#        subject: Your ${{github.repository}} Repo Commit History
#        to: jfuentes@zivra.com
#        from: Jorge Fuentes <jfuentes@zivra.com>
#        body: You're getting this email because the workflow run for ${{github.repository}} completed successfully!. Please check the attached report.
#        ignore_cert: true
#        convert_markdown: true
#        attachments: ./summarized.csv
#        priority: low
