# This workflow creates a Change Request ticket on Service Now

name: create_crf

on:
# Enable to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create_crf_via_api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: display commit message
      run: echo  echo ${{toJSON(github.event.commits[0].message)}}
    - name: create string
      run: |
        MY_STRING=$(cat << EOF
        first line
        second line
        third line
        EOF
        )
        echo "MY_STRING<<EOF" >> $GITHUB_ENV
        echo "$MY_STRING" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      id: my_string
    - name: display string
      run: |
        echo "The string is: ${{ env.MY_STRING }}"
    - name: Send API to SN
      run: curl "https://dev135802.service-now.com/api/sn_chg_rest/change/normal" --request POST --header "Accept:application/json" --header "Content-Type:application/json" --data "{\"short_description\":\"Testing new CRF from GH\",\"description\":\"This is the text of line one,\\n and this is line two \"}" \--user ${{secrets.SN_USER}}:${{secrets.SN_PASSWD}}
    #  run: curl "https://dev135802.service-now.com/api/sn_chg_rest/change/normal" --request POST --header "Accept:application/json" --header "Content-Type:application/json" --data "{\"short_description\":\"Testing new CRF from GH\",\"description\":\"All the squashed commits in here\"}" \--user ${{secrets.SN_USER}}:${{secrets.SN_PASSWD}}
    #  run: curl "https://dev135802.service-now.com/api/sn_chg_rest/change/normal" \    
#       curl "https://igtest.service-now.com/api/now/table/change_request" \
#      run: | 
#        curl "https://dev135802.service-now.com/api/sn_chg_rest/change/normal" \    
#          --request POST \
#          --header "Accept:application/json" \
#          --header "Content-Type:application/json" \
#          --data "{\"short_description\":\"Testing new CRF with info\",\"type\":\"Planned\",\"description\":${{ env.MY_STRING }}}" \
#          --user ${{secrets.SN_USER}}:${{secrets.SN_PASSWD}}
