#This workflow retrieves Team information and gets the Team ID 
name: Get_teams_information

on:
  # Enable to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Enable to run this workflow when a a push is made
  push:

env:
    GH_TOKEN: ${{ github.token }}
    ORGANIZATION: "tastyworks"
    TEAM_NAME: "Change-Management"
    API_TOKEN: ${{ secrets.API_TOKEN }}

jobs:
  get_team_information:
    runs-on: ubuntu-latest

    steps:
    - name: Get Team Information
      run: |
        curl -H "Authorization: token ${{ env.API_TOKEN }}" https://api.github.com/orgs/${{ env.ORGANIZATION }}/teams > out.json
        jq --arg team_name ${{ env.TEAM_NAME }} -r '[.[] | select(.name == $team_name )] | ( .[] | .id  )' out.json >> team_id.txt
        TEAM_ID=$(cat team_id.txt)
        echo "The Team Id is: " $TEAM_ID
        curl -H "Authorization: token ${{ secrets.API_TOKEN }}" https://api.github.com/teams/$TEAM_ID/repos > repo_list.json
        echo "List repositories in team:"
        cat repo_list.json | grep "full_name"
