name: SecretScan

on:
  schedule:
    - cron: "30 * * * *"

#on: [push]

jobs:
  scan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - uses: max/secret-scan@master
    - name: Run a one-line script
      run: echo Hello, world!
    # - name: Run a multi-line script
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.
    # - name: Secret Scan
    #   uses: max/secret-scan@master
