# This workflow creates a report of the Pull Requests of the repository

name: PR_Report

on:
# Enable to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '05 02 * * *'

jobs:
  pr_report_Actions:
    runs-on: ubuntu-latest
    name: Get Pull Requests with Actions
    steps:
      - name: listPullRequests
        uses: buildsville/list-pull-requests@v1
        id: list
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: '[]'
      - name: report_result
        run: echo '${{ steps.list.outputs.pulls }}'  
        
  pr_report_api:
    runs-on: ubuntu-latest
    name: Get Pull Requests with API
    steps:
      - name: GetPullRequests
        run: curl  https://api.github.com/repos/Zivra/availability-service/pulls -H "Authorization:token ${{secrets.API_TOKEN}}" | jq '.[] | {user:.user.login,created:.created_at,Assignees:.assignees}'
      #  run: curl 'https://api.github.com/repos/stedolan/jq/commits?per_page=5' | jq '.'
